### ISSUE TITLE
Pasting above the line

### ISSUE THREAD

**Issue by dodozhang21** [larsch/eclipse-linecopypaste#3]
Hi, is the following behavior intended?

If I select at the end of a line and do ctrl+v, it pastes the line above the end of the line instead of below it. I thought that was a bit odd.

Expected:
Put my cursor at the beginning of a line, ctrl+v, paste line above
Put my cursor at the end of a line, ctrl+v, paste the line below

**Comment by larsch** [comment]
I just checked with the Visual Studio 2008, and that particular behaviour is consistent with it. No matter what position the cursor has on a line, the line will be pasted above. What i DID notice was that the cursor would be left in the same position after the paste, so I changed the plugin to do the same. Before this change, it would leave the cursor at the start of the following line. It seems that this is a bit more intituitive.
